---
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    targets:
      - go_first_class
    flags:
      - -trimpath
    ldflags:
      - -s -w

changelog:
  disable: true

archives:
  - format_overrides:
      - goos: windows
        formats: zip

checksum:
  name_template: checksums.sha256.txt
  algorithm: sha256

report_sizes: true

release:
  name_template: "v{{ .Version }}"
