---
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_386
      - linux_amd64
      - linux_arm
      - linux_arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/yegor-usoltsev/cronctl/internal/version.Version=v{{ .Version }}

checksum:
  name_template: checksums.sha256.txt
  algorithm: sha256

report_sizes: true

release:
  name_template: "v{{ .Version }}"
